spring:
  port: 8100
  application:
    name: postgres-service
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
